name: 자동 뉴스 요약 및 스레드 생성

on:
  schedule:
    - cron: '18 6 * * *'  # 한국시간 오전 9시
  workflow_dispatch:

jobs:
  news-summary:
    runs-on: ubuntu-latest

    steps:
    - name: 코드 체크아웃
      uses: actions/checkout@v3

    - name: Python 설정
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: 라이브러리 설치
      run: |
        pip install -r requirements.txt

    - name: 뉴스 요약 실행
      env:
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
      run: |
        python news_summarizer.py

